FROM node:18.16-bullseye

WORKDIR /app

COPY . .

#RUN apt-get update
#RUN apt-get install -f build-essential gcc
#RUN npm install -g npm nodemon node-gyp ts-node
#RUN export PYTHON=/usr/bin/python3.9
#RUN npm install

#CMD ["npm", "run", "start:prod"]
CMD ["sleep", "infinity"]